language: node_js
node_js:
  - '14'
if: branch = master OR tag IS present
before_install:
  - npm i -g chrome-webstore-upload-cli@2.1.0 web-ext-submit@6.1.0
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
notifications:
  email:
    - 79917148leslie@gmail.com