language: node_js
node_js:
  - '12'
if: branch = master OR tag IS present
before_install:
  - npm i -g chrome-webstore-upload-cli web-ext-submit
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
notifications:
  email:
    - 79917148leslie@gmail.com